In [1]:
import leafmap
import geopandas as gpd
import pandas as pd

In [2]:
df = gpd.read_file('Stadtteile/Düsseldorf_Stadtteile.shp')

columns_drop = ["OBJECTID", "Quelle", "Stand", "Stadtbezir", "Stadtteil", "SHAPE_Leng", "SHAPE_Area"]
df.drop(labels = columns_drop, axis = "columns", inplace = True)

df.rename(columns={'Name':'Neighborhood','geometry':'GEO'}, inplace=True)

In [3]:
df

      Neighborhood                                                GEO
0         Wittlaer  POLYGON Z ((753213.545 6676946.480 0.000, 7532...
1        Angermund  POLYGON Z ((758032.788 6682177.206 0.000, 7580...
2           Lörick  POLYGON Z ((750972.572 6665996.186 0.000, 7507...
3           Heerdt  POLYGON Z ((749803.703 6663442.957 0.000, 7496...
4       Oberkassel  POLYGON Z ((753486.019 6662425.887 0.000, 7534...
5     Niederkassel  POLYGON Z ((753437.079 6662969.087 0.000, 7528...
6         Golzheim  POLYGON Z ((754975.370 6664275.935 0.000, 7549...
7        Derendorf  POLYGON Z ((756549.378 6664501.726 0.000, 7562...
8       Pempelfort  POLYGON Z ((756750.257 6662093.973 0.000, 7567...
9        Carlstadt  POLYGON Z ((754265.923 6661187.584 0.000, 7542...
10    Flingern Süd  POLYGON Z ((759639.415 6660996.694 0.000, 7596...
11       Düsseltal  POLYGON Z ((759379.585 6663593.022 0.000, 7593...
12  Friedrichstadt  POLYGON Z ((756099.313 6659797.304 0.000, 7560...
13           Hafen  POLYGON Z ((753157.502 6660154.355 0.000, 7531...
14            Hamm  POLYGON Z ((752359.736 6658596.959 0.000, 7523...
15    Volmerswerth  POLYGON Z ((754061.676 6654117.974 0.000, 7540...
16        Altstadt  POLYGON Z ((754442.628 6662145.847 0.000, 7544...
17            Rath  POLYGON Z ((764474.094 6668916.227 0.000, 7642...
18    Mörsenbroich  POLYGON Z ((759439.607 6665804.894 0.000, 7594...
19       Knittkuhl  POLYGON Z ((765738.693 6667936.950 0.000, 7657...
20      Grafenberg  POLYGON Z ((761361.050 6663218.917 0.000, 7612...
21       Ludenberg  POLYGON Z ((765774.350 6667619.575 0.000, 7657...
22      Hubbelrath  POLYGON Z ((772549.908 6669646.756 0.000, 7725...
23      Lierenfeld  POLYGON Z ((761428.290 6660302.588 0.000, 7614...
24           Eller  POLYGON Z ((765829.917 6654974.796 0.000, 7657...
25      Vennhausen  POLYGON Z ((765936.009 6657844.412 0.000, 7659...
26       Unterbach  POLYGON Z ((770475.301 6655449.399 0.000, 7704...
27         Hassels  POLYGON Z ((768743.571 6652617.936 0.000, 7687...
28        Reisholz  POLYGON Z ((764902.589 6651480.812 0.000, 7648...
29         Benrath  POLYGON Z ((768126.375 6650914.481 0.000, 7681...
30           Itter  POLYGON Z ((760198.075 6648922.786 0.000, 7601...
31      Holthausen  POLYGON Z ((763128.453 6654109.221 0.000, 7629...
32    Kaiserswerth  POLYGON Z ((751682.305 6675914.331 0.000, 7516...
33         Stockum  POLYGON Z ((752856.956 6667720.217 0.000, 7528...
34          Kalkum  POLYGON Z ((758915.616 6678261.194 0.000, 7589...
35   Lichtenbroich  POLYGON Z ((757403.286 6672230.589 0.000, 7574...
36       Unterrath  POLYGON Z ((756716.431 6670121.356 0.000, 7566...
37        Lohausen  POLYGON Z ((757384.752 6672244.613 0.000, 7569...
38        Oberbilk  POLYGON Z ((759859.254 6655984.513 0.000, 7598...
39      Stadtmitte  POLYGON Z ((756926.323 6661181.118 0.000, 7569...
40       Unterbilk  POLYGON Z ((754405.383 6660124.170 0.000, 7544...
41     Himmelgeist  POLYGON Z ((758986.282 6647095.447 0.000, 7589...
42           Flehe  POLYGON Z ((757412.915 6653306.073 0.000, 7573...
43         Wersten  POLYGON Z ((761894.592 6654733.872 0.000, 7618...
44            Bilk  POLYGON Z ((757905.641 6655553.630 0.000, 7578...
45          Garath  POLYGON Z ((770134.072 6646109.085 0.000, 7699...
46       Hellerhof  POLYGON Z ((770900.653 6645486.148 0.000, 7708...
47       Urdenbach  POLYGON Z ((767670.141 6645256.420 0.000, 7676...
48   Flingern Nord  POLYGON Z ((761399.130 6660382.897 0.000, 7613...
49      Gerresheim  POLYGON Z ((765883.253 6661727.804 0.000, 7658...

In [4]:
df.crs

<Derived Projected CRS: EPSG:3857>
Name: WGS 84 / Pseudo-Mercator
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: World between 85.06°S and 85.06°N.
- bounds: (-180.0, -85.06, 180.0, 85.06)
Coordinate Operation:
- name: Popular Visualisation Pseudo-Mercator
- method: Popular Visualisation Pseudo Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [5]:
df = df.set_geometry("GEO")
df = df.to_crs(4326)

df.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [6]:
noise_df = gpd.read_file('noise_dus.csv')

nonsense = ["Index", "geometry"]
noise_df.drop(labels = nonsense, axis = "columns", inplace = True)

noise_df["Bezirk"] = noise_df["Bezirk"].map(lambda x: x.replace("ÃƒÅ¸", "ß").replace("ÃƒÂ¼", "ü"))
noise_df.rename(columns={'Bezirk': 'Address'}, inplace=True)

noise_df

,Address,DB_TAG,DB_NACHT,Latitude,Longitude
0,"Aachener Straße 1, Düsseldorf, Germany",68,62,51.2075921,6.7765
1,"Aachener Straße 10, Düsseldorf, Germany",68,61,51.207128,6.7764358
2,"Aachener Straße 101, Düsseldorf, Germany",70,63,51.2025326,6.77114559698015
3,"Aachener Straße 103, Düsseldorf, Germany",70,62,51.2024275499999,6.77107674218849
4,"Aachener Straße 105, Düsseldorf, Germany",69,62,51.2023321,6.7711066
...,...,...,...,...,...
78826,"Zypressenweg 15, Düsseldorf, Germany",54,47,,
78827,"Zypressenweg 3, Düsseldorf, Germany",57,50,,
78828,"Zypressenweg 5, Düsseldorf, Germany",55,48,,
78829,"Zypressenweg 7, Düsseldorf, Germany",55,48,,
78830,"Zypressenweg 9, Düsseldorf, Germany",55,48,,

In [7]:
noise_df.dtypes

Address      object
DB_TAG       object
DB_NACHT     object
Latitude     object
Longitude    object
dtype: object

In [8]:
noise_df["Latitude"] = pd.to_numeric(noise_df["Latitude"], errors='coerce')
noise_df["Longitude"] = pd.to_numeric(noise_df["Longitude"], errors='coerce')

noise_df = noise_df.dropna(how='any',axis=0) 
noise_df

,Address,DB_TAG,DB_NACHT,Latitude,Longitude
0,"Aachener Straße 1, Düsseldorf, Germany",68,62,51.207592,6.776500
1,"Aachener Straße 10, Düsseldorf, Germany",68,61,51.207128,6.776436
2,"Aachener Straße 101, Düsseldorf, Germany",70,63,51.202533,6.771146
3,"Aachener Straße 103, Düsseldorf, Germany",70,62,51.202428,6.771077
4,"Aachener Straße 105, Düsseldorf, Germany",69,62,51.202332,6.771107
...,...,...,...,...,...
78242,"Zietenstraße 27, Düsseldorf, Germany",53,45,51.242225,6.776998
78243,"Zietenstraße 29, Düsseldorf, Germany",53,45,51.242274,6.777171
78244,"Zietenstraße 3, Düsseldorf, Germany",57,48,51.241556,6.774812
78245,"Zietenstraße 30, Düsseldorf, Germany",54,45,51.242552,6.776789
78246,"Zietenstraße 31, Düsseldorf, Germany",53,45,51.242345,6.777385

In [9]:
gdf_listings = gpd.GeoDataFrame(noise_df, geometry=gpd.points_from_xy(noise_df.Longitude, noise_df.Latitude))

gdf_listings

,Address,DB_TAG,DB_NACHT,Latitude,Longitude,geometry
0,"Aachener Straße 1, Düsseldorf, Germany",68,62,51.207592,6.776500,POINT (6.77650 51.20759)
1,"Aachener Straße 10, Düsseldorf, Germany",68,61,51.207128,6.776436,POINT (6.77644 51.20713)
2,"Aachener Straße 101, Düsseldorf, Germany",70,63,51.202533,6.771146,POINT (6.77115 51.20253)
3,"Aachener Straße 103, Düsseldorf, Germany",70,62,51.202428,6.771077,POINT (6.77108 51.20243)
4,"Aachener Straße 105, Düsseldorf, Germany",69,62,51.202332,6.771107,POINT (6.77111 51.20233)
...,...,...,...,...,...,...
78242,"Zietenstraße 27, Düsseldorf, Germany",53,45,51.242225,6.776998,POINT (6.77700 51.24222)
78243,"Zietenstraße 29, Düsseldorf, Germany",53,45,51.242274,6.777171,POINT (6.77717 51.24227)
78244,"Zietenstraße 3, Düsseldorf, Germany",57,48,51.241556,6.774812,POINT (6.77481 51.24156)
78245,"Zietenstraße 30, Düsseldorf, Germany",54,45,51.242552,6.776789,POINT (6.77679 51.24255)
78246,"Zietenstraße 31, Düsseldorf, Germany",53,45,51.242345,6.777385,POINT (6.77738 51.24235)

In [10]:
gdf_listings.crs = "EPSG:4326"

In [11]:
gdf_listings.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [12]:
import numpy as np

df['GEO'] = df.geometry
sjoined = gpd.sjoin(gdf_listings,df, op='within')
sjoined.drop(['index_right'], axis = "columns", inplace = True)
#sjoined = sjoined.set_index('Neighborhood')
#sjoined = sjoined.sample(20)

sjoined['DB_NACHT'] = pd.to_numeric(sjoined['DB_NACHT'], errors='coerce')
sjoined['DB_TAG'] = pd.to_numeric(sjoined['DB_TAG'], errors='coerce')

sjoined['DB_TAG'] = sjoined['DB_TAG'].replace([np.inf, -np.inf], np.nan).astype('Int64')
sjoined['DB_NACHT'] = sjoined['DB_NACHT'].replace([np.inf, -np.inf], np.nan).astype('Int64')


sjoined

,Address,DB_TAG,DB_NACHT,Latitude,Longitude,geometry,Neighborhood
0,"Aachener Straße 1, Düsseldorf, Germany",68,62,51.207592,6.776500,POINT (6.77650 51.20759),Bilk
1,"Aachener Straße 10, Düsseldorf, Germany",68,61,51.207128,6.776436,POINT (6.77644 51.20713),Bilk
2,"Aachener Straße 101, Düsseldorf, Germany",70,63,51.202533,6.771146,POINT (6.77115 51.20253),Bilk
3,"Aachener Straße 103, Düsseldorf, Germany",70,62,51.202428,6.771077,POINT (6.77108 51.20243),Bilk
4,"Aachener Straße 105, Düsseldorf, Germany",69,62,51.202332,6.771107,POINT (6.77111 51.20233),Bilk
...,...,...,...,...,...,...,...
77531,"Wolfgang-Borchert-Straße 5, Düsseldorf, Germany",53,45,51.128947,6.899065,POINT (6.89907 51.12895),Hellerhof
77532,"Wolfgang-Borchert-Straße 6, Düsseldorf, Germany",52,44,51.128526,6.899297,POINT (6.89930 51.12853),Hellerhof
77533,"Wolfgang-Borchert-Straße 7, Düsseldorf, Germany",52,45,51.128948,6.898943,POINT (6.89894 51.12895),Hellerhof
77534,"Wolfgang-Borchert-Straße 8, Düsseldorf, Germany",52,44,51.128527,6.899216,POINT (6.89922 51.12853),Hellerhof
77535,"Wolfgang-Borchert-Straße 9, Düsseldorf, Germany",52,45,51.128949,6.898820,POINT (6.89882 51.12895),Hellerhof

In [13]:
total_DB_TAG = sjoined['DB_TAG'].groupby(sjoined['Neighborhood'])

meanvaluetag = total_DB_TAG.mean()

Bezirk_TAG = pd.DataFrame(meanvaluetag).reset_index() 
Bezirk_TAG

      Neighborhood     DB_TAG
0         Altstadt  57.699789
1        Angermund  51.446281
2          Benrath  58.261646
3             Bilk  59.179613
4        Carlstadt  60.528736
5        Derendorf  60.341991
6        Düsseltal  59.883854
7            Eller  58.116588
8            Flehe   60.15493
9    Flingern Nord  59.615031
10    Flingern Süd  60.724868
11  Friedrichstadt   62.77688
12          Garath  56.731655
13      Gerresheim  55.805616
14        Golzheim  60.170624
15      Grafenberg  58.025992
16           Hafen  60.176136
17            Hamm  57.675214
18         Hassels  58.989703
19          Heerdt  60.602572
20       Hellerhof  56.768185
21     Himmelgeist  53.546729
22      Holthausen  57.566265
23      Hubbelrath  55.416364
24           Itter  54.362319
25    Kaiserswerth  56.673616
26          Kalkum  53.969336
27       Knittkuhl  50.488889
28   Lichtenbroich  57.475836
29      Lierenfeld  58.183607
30        Lohausen  55.240975
31       Ludenberg  54.730999
32          Lörick  53.602421
33    Mörsenbroich  56.069795
34    Niederkassel  56.610024
35        Oberbilk  60.624071
36      Oberkassel  58.515371
37      Pempelfort  61.305106
38            Rath  57.829161
39        Reisholz   56.64658
40      Stadtmitte  63.723034
41         Stockum  58.012687
42       Unterbach  55.217789
43       Unterbilk  61.198052
44       Unterrath  56.680621
45       Urdenbach  54.310818
46      Vennhausen  55.254886
47    Volmerswerth  55.661765
48         Wersten  57.000257
49        Wittlaer  53.339965

In [14]:
df2 = gpd.GeoDataFrame(Bezirk_TAG.merge(df, on='Neighborhood', how='left'))
df2.rename(columns={'DB_TAG':'Avg. DB_TAG','GEO':'geometry'}, inplace=True)
df2

,Neighborhood,Avg. DB_TAG,geometry
0,Altstadt,57.699789,"POLYGON Z ((6.77727 51.23037 0.00000, 6.77728 ..."
1,Angermund,51.446281,"POLYGON Z ((6.80952 51.34292 0.00000, 6.80943 ..."
2,Benrath,58.261646,"POLYGON Z ((6.90020 51.16715 0.00000, 6.89997 ..."
3,Bilk,59.179613,"POLYGON Z ((6.80838 51.19328 0.00000, 6.80811 ..."
4,Carlstadt,60.528736,"POLYGON Z ((6.77569 51.22498 0.00000, 6.77565 ..."
5,Derendorf,60.341991,"POLYGON Z ((6.79620 51.24362 0.00000, 6.79372 ..."
6,Düsseltal,59.883854,"POLYGON Z ((6.82162 51.23851 0.00000, 6.82160 ..."
7,Eller,58.116588,"POLYGON Z ((6.87957 51.19002 0.00000, 6.87853 ..."
8,Flehe,60.15493,"POLYGON Z ((6.80396 51.18062 0.00000, 6.80367 ..."
9,Flingern Nord,59.615031,"POLYGON Z ((6.83976 51.22046 0.00000, 6.83952 ..."
10,Flingern Süd,60.724868,"POLYGON Z ((6.82396 51.22391 0.00000, 6.82386 ..."
11,Friedrichstadt,62.77688,"POLYGON Z ((6.79216 51.21716 0.00000, 6.79204 ..."
12,Garath,56.731655,"POLYGON Z ((6.91823 51.14008 0.00000, 6.91627 ..."
13,Gerresheim,55.805616,"POLYGON Z ((6.88005 51.22802 0.00000, 6.87998 ..."
14,Golzheim,60.170624,"POLYGON Z ((6.78206 51.24235 0.00000, 6.78196 ..."
15,Grafenberg,58.025992,"POLYGON Z ((6.83942 51.23641 0.00000, 6.83817 ..."
16,Hafen,60.176136,"POLYGON Z ((6.76573 51.21917 0.00000, 6.76574 ..."
17,Hamm,57.675214,"POLYGON Z ((6.75856 51.21041 0.00000, 6.75853 ..."
18,Hassels,58.989703,"POLYGON Z ((6.90574 51.17675 0.00000, 6.90570 ..."
19,Heerdt,60.602572,"POLYGON Z ((6.73560 51.23767 0.00000, 6.73399 ..."
20,Hellerhof,56.768185,"POLYGON Z ((6.92512 51.13657 0.00000, 6.92478 ..."
21,Himmelgeist,53.546729,"POLYGON Z ((6.81809 51.14564 0.00000, 6.81803 ..."
22,Holthausen,57.566265,"POLYGON Z ((6.85530 51.18514 0.00000, 6.85408 ..."
23,Hubbelrath,55.416364,"POLYGON Z ((6.93993 51.27255 0.00000, 6.93985 ..."
24,Itter,54.362319,"POLYGON Z ((6.82898 51.15593 0.00000, 6.82890 ..."
25,Kaiserswerth,56.673616,"POLYGON Z ((6.75248 51.30776 0.00000, 6.75246 ..."
26,Kalkum,53.969336,"POLYGON Z ((6.81745 51.32094 0.00000, 6.81744 ..."
27,Knittkuhl,50.488889,"POLYGON Z ((6.87875 51.26294 0.00000, 6.87894 ..."
28,Lichtenbroich,57.475836,"POLYGON Z ((6.80387 51.28707 0.00000, 6.80387 ..."
29,Lierenfeld,58.183607,"POLYGON Z ((6.84003 51.22000 0.00000, 6.83979 ..."
30,Lohausen,55.240975,"POLYGON Z ((6.80370 51.28715 0.00000, 6.79951 ..."
31,Ludenberg,54.730999,"POLYGON Z ((6.87907 51.26115 0.00000, 6.87905 ..."
32,Lörick,53.602421,"POLYGON Z ((6.74610 51.25203 0.00000, 6.74380 ..."
33,Mörsenbroich,56.069795,"POLYGON Z ((6.82216 51.25095 0.00000, 6.82216 ..."
34,Niederkassel,56.610024,"POLYGON Z ((6.76824 51.23500 0.00000, 6.76261 ..."
35,Oberbilk,60.624071,"POLYGON Z ((6.82593 51.19570 0.00000, 6.82593 ..."
36,Oberkassel,58.515371,"POLYGON Z ((6.76868 51.23195 0.00000, 6.76868 ..."
37,Pempelfort,61.305106,"POLYGON Z ((6.79800 51.23008 0.00000, 6.79804 ..."
38,Rath,57.829161,"POLYGON Z ((6.86739 51.26844 0.00000, 6.86574 ..."
39,Reisholz,56.64658,"POLYGON Z ((6.87124 51.17034 0.00000, 6.87032 ..."
40,Stadtmitte,63.723034,"POLYGON Z ((6.79958 51.22495 0.00000, 6.79952 ..."
41,Stockum,58.012687,"POLYGON Z ((6.76303 51.26172 0.00000, 6.76303 ..."
42,Unterbach,55.217789,"POLYGON Z ((6.92130 51.19269 0.00000, 6.92104 ..."
43,Unterbilk,61.198052,"POLYGON Z ((6.77694 51.21900 0.00000, 6.77694 ..."
44,Unterrath,56.680621,"POLYGON Z ((6.79770 51.27522 0.00000, 6.79669 ..."
45,Urdenbach,54.310818,"POLYGON Z ((6.89610 51.13527 0.00000, 6.89609 ..."
46,Vennhausen,55.254886,"POLYGON Z ((6.88052 51.20617 0.00000, 6.88026 ..."
47,Volmerswerth,55.661765,"POLYGON Z ((6.77385 51.18519 0.00000, 6.77383 ..."
48,Wersten,57.000257,"POLYGON Z ((6.84422 51.18866 0.00000, 6.84421 ..."
49,Wittlaer,53.339965,"POLYGON Z ((6.76623 51.31355 0.00000, 6.76617 ..."

In [15]:
df2 = gpd.GeoDataFrame(Bezirk_TAG.merge(df, on='Neighborhood', how='left'))
df2.rename(columns={'DB_TAG':'Avg. DB_TAG','GEO':'geometry'}, inplace=True)
df2['Avg. DB_TAG'] = df2['Avg. DB_TAG'].round(decimals = 2)
df2

,Neighborhood,Avg. DB_TAG,geometry
0,Altstadt,57.7,"POLYGON Z ((6.77727 51.23037 0.00000, 6.77728 ..."
1,Angermund,51.45,"POLYGON Z ((6.80952 51.34292 0.00000, 6.80943 ..."
2,Benrath,58.26,"POLYGON Z ((6.90020 51.16715 0.00000, 6.89997 ..."
3,Bilk,59.18,"POLYGON Z ((6.80838 51.19328 0.00000, 6.80811 ..."
4,Carlstadt,60.53,"POLYGON Z ((6.77569 51.22498 0.00000, 6.77565 ..."
5,Derendorf,60.34,"POLYGON Z ((6.79620 51.24362 0.00000, 6.79372 ..."
6,Düsseltal,59.88,"POLYGON Z ((6.82162 51.23851 0.00000, 6.82160 ..."
7,Eller,58.12,"POLYGON Z ((6.87957 51.19002 0.00000, 6.87853 ..."
8,Flehe,60.15,"POLYGON Z ((6.80396 51.18062 0.00000, 6.80367 ..."
9,Flingern Nord,59.62,"POLYGON Z ((6.83976 51.22046 0.00000, 6.83952 ..."
10,Flingern Süd,60.72,"POLYGON Z ((6.82396 51.22391 0.00000, 6.82386 ..."
11,Friedrichstadt,62.78,"POLYGON Z ((6.79216 51.21716 0.00000, 6.79204 ..."
12,Garath,56.73,"POLYGON Z ((6.91823 51.14008 0.00000, 6.91627 ..."
13,Gerresheim,55.81,"POLYGON Z ((6.88005 51.22802 0.00000, 6.87998 ..."
14,Golzheim,60.17,"POLYGON Z ((6.78206 51.24235 0.00000, 6.78196 ..."
15,Grafenberg,58.03,"POLYGON Z ((6.83942 51.23641 0.00000, 6.83817 ..."
16,Hafen,60.18,"POLYGON Z ((6.76573 51.21917 0.00000, 6.76574 ..."
17,Hamm,57.68,"POLYGON Z ((6.75856 51.21041 0.00000, 6.75853 ..."
18,Hassels,58.99,"POLYGON Z ((6.90574 51.17675 0.00000, 6.90570 ..."
19,Heerdt,60.6,"POLYGON Z ((6.73560 51.23767 0.00000, 6.73399 ..."
20,Hellerhof,56.77,"POLYGON Z ((6.92512 51.13657 0.00000, 6.92478 ..."
21,Himmelgeist,53.55,"POLYGON Z ((6.81809 51.14564 0.00000, 6.81803 ..."
22,Holthausen,57.57,"POLYGON Z ((6.85530 51.18514 0.00000, 6.85408 ..."
23,Hubbelrath,55.42,"POLYGON Z ((6.93993 51.27255 0.00000, 6.93985 ..."
24,Itter,54.36,"POLYGON Z ((6.82898 51.15593 0.00000, 6.82890 ..."
25,Kaiserswerth,56.67,"POLYGON Z ((6.75248 51.30776 0.00000, 6.75246 ..."
26,Kalkum,53.97,"POLYGON Z ((6.81745 51.32094 0.00000, 6.81744 ..."
27,Knittkuhl,50.49,"POLYGON Z ((6.87875 51.26294 0.00000, 6.87894 ..."
28,Lichtenbroich,57.48,"POLYGON Z ((6.80387 51.28707 0.00000, 6.80387 ..."
29,Lierenfeld,58.18,"POLYGON Z ((6.84003 51.22000 0.00000, 6.83979 ..."
30,Lohausen,55.24,"POLYGON Z ((6.80370 51.28715 0.00000, 6.79951 ..."
31,Ludenberg,54.73,"POLYGON Z ((6.87907 51.26115 0.00000, 6.87905 ..."
32,Lörick,53.6,"POLYGON Z ((6.74610 51.25203 0.00000, 6.74380 ..."
33,Mörsenbroich,56.07,"POLYGON Z ((6.82216 51.25095 0.00000, 6.82216 ..."
34,Niederkassel,56.61,"POLYGON Z ((6.76824 51.23500 0.00000, 6.76261 ..."
35,Oberbilk,60.62,"POLYGON Z ((6.82593 51.19570 0.00000, 6.82593 ..."
36,Oberkassel,58.52,"POLYGON Z ((6.76868 51.23195 0.00000, 6.76868 ..."
37,Pempelfort,61.31,"POLYGON Z ((6.79800 51.23008 0.00000, 6.79804 ..."
38,Rath,57.83,"POLYGON Z ((6.86739 51.26844 0.00000, 6.86574 ..."
39,Reisholz,56.65,"POLYGON Z ((6.87124 51.17034 0.00000, 6.87032 ..."
40,Stadtmitte,63.72,"POLYGON Z ((6.79958 51.22495 0.00000, 6.79952 ..."
41,Stockum,58.01,"POLYGON Z ((6.76303 51.26172 0.00000, 6.76303 ..."
42,Unterbach,55.22,"POLYGON Z ((6.92130 51.19269 0.00000, 6.92104 ..."
43,Unterbilk,61.2,"POLYGON Z ((6.77694 51.21900 0.00000, 6.77694 ..."
44,Unterrath,56.68,"POLYGON Z ((6.79770 51.27522 0.00000, 6.79669 ..."
45,Urdenbach,54.31,"POLYGON Z ((6.89610 51.13527 0.00000, 6.89609 ..."
46,Vennhausen,55.25,"POLYGON Z ((6.88052 51.20617 0.00000, 6.88026 ..."
47,Volmerswerth,55.66,"POLYGON Z ((6.77385 51.18519 0.00000, 6.77383 ..."
48,Wersten,57.0,"POLYGON Z ((6.84422 51.18866 0.00000, 6.84421 ..."
49,Wittlaer,53.34,"POLYGON Z ((6.76623 51.31355 0.00000, 6.76617 ..."

In [16]:
total_DB_NACHT = sjoined['DB_NACHT'].groupby(sjoined['Neighborhood'])

meanvaluenacht = total_DB_NACHT.mean()

Bezirk_NACHT = pd.DataFrame(meanvaluenacht).reset_index()
Bezirk_NACHT

      Neighborhood   DB_NACHT
0         Altstadt  48.217759
1        Angermund  42.895741
2          Benrath  50.305124
3             Bilk  51.136587
4        Carlstadt  51.890805
5        Derendorf  52.222635
6        Düsseltal  51.828861
7            Eller  50.108033
8            Flehe  52.932394
9    Flingern Nord  51.226994
10    Flingern Süd  52.793651
11  Friedrichstadt  54.887631
12          Garath  49.299411
13      Gerresheim  47.420331
14        Golzheim  51.630607
15      Grafenberg  49.818057
16           Hafen  52.380682
17            Hamm   49.04416
18         Hassels  51.238038
19          Heerdt  53.483601
20       Hellerhof  49.341944
21     Himmelgeist  46.018692
22      Holthausen  49.924699
23      Hubbelrath  47.645455
24           Itter  47.204969
25    Kaiserswerth  48.611075
26          Kalkum  45.483816
27       Knittkuhl  42.066667
28   Lichtenbroich  50.006506
29      Lierenfeld  50.019672
30        Lohausen  47.333935
31       Ludenberg  46.111016
32          Lörick  45.645251
33    Mörsenbroich  47.952467
34    Niederkassel  49.013447
35        Oberbilk  52.549721
36      Oberkassel  50.722032
37      Pempelfort  53.410959
38            Rath  50.001757
39        Reisholz   48.47557
40      Stadtmitte  55.388309
41         Stockum  49.762687
42       Unterbach  46.885546
43       Unterbilk  52.964286
44       Unterrath  48.799368
45       Urdenbach    46.1933
46      Vennhausen  46.570847
47    Volmerswerth  47.922794
48         Wersten  49.582969
49        Wittlaer  45.046811

In [17]:
df3 = gpd.GeoDataFrame(Bezirk_NACHT.merge(df, on='Neighborhood', how='left'))
df3.rename(columns={'DB_NACHT':'Avg. DB_NACHT','GEO':'geometry'}, inplace=True)
df3

,Neighborhood,Avg. DB_NACHT,geometry
0,Altstadt,48.217759,"POLYGON Z ((6.77727 51.23037 0.00000, 6.77728 ..."
1,Angermund,42.895741,"POLYGON Z ((6.80952 51.34292 0.00000, 6.80943 ..."
2,Benrath,50.305124,"POLYGON Z ((6.90020 51.16715 0.00000, 6.89997 ..."
3,Bilk,51.136587,"POLYGON Z ((6.80838 51.19328 0.00000, 6.80811 ..."
4,Carlstadt,51.890805,"POLYGON Z ((6.77569 51.22498 0.00000, 6.77565 ..."
5,Derendorf,52.222635,"POLYGON Z ((6.79620 51.24362 0.00000, 6.79372 ..."
6,Düsseltal,51.828861,"POLYGON Z ((6.82162 51.23851 0.00000, 6.82160 ..."
7,Eller,50.108033,"POLYGON Z ((6.87957 51.19002 0.00000, 6.87853 ..."
8,Flehe,52.932394,"POLYGON Z ((6.80396 51.18062 0.00000, 6.80367 ..."
9,Flingern Nord,51.226994,"POLYGON Z ((6.83976 51.22046 0.00000, 6.83952 ..."
10,Flingern Süd,52.793651,"POLYGON Z ((6.82396 51.22391 0.00000, 6.82386 ..."
11,Friedrichstadt,54.887631,"POLYGON Z ((6.79216 51.21716 0.00000, 6.79204 ..."
12,Garath,49.299411,"POLYGON Z ((6.91823 51.14008 0.00000, 6.91627 ..."
13,Gerresheim,47.420331,"POLYGON Z ((6.88005 51.22802 0.00000, 6.87998 ..."
14,Golzheim,51.630607,"POLYGON Z ((6.78206 51.24235 0.00000, 6.78196 ..."
15,Grafenberg,49.818057,"POLYGON Z ((6.83942 51.23641 0.00000, 6.83817 ..."
16,Hafen,52.380682,"POLYGON Z ((6.76573 51.21917 0.00000, 6.76574 ..."
17,Hamm,49.04416,"POLYGON Z ((6.75856 51.21041 0.00000, 6.75853 ..."
18,Hassels,51.238038,"POLYGON Z ((6.90574 51.17675 0.00000, 6.90570 ..."
19,Heerdt,53.483601,"POLYGON Z ((6.73560 51.23767 0.00000, 6.73399 ..."
20,Hellerhof,49.341944,"POLYGON Z ((6.92512 51.13657 0.00000, 6.92478 ..."
21,Himmelgeist,46.018692,"POLYGON Z ((6.81809 51.14564 0.00000, 6.81803 ..."
22,Holthausen,49.924699,"POLYGON Z ((6.85530 51.18514 0.00000, 6.85408 ..."
23,Hubbelrath,47.645455,"POLYGON Z ((6.93993 51.27255 0.00000, 6.93985 ..."
24,Itter,47.204969,"POLYGON Z ((6.82898 51.15593 0.00000, 6.82890 ..."
25,Kaiserswerth,48.611075,"POLYGON Z ((6.75248 51.30776 0.00000, 6.75246 ..."
26,Kalkum,45.483816,"POLYGON Z ((6.81745 51.32094 0.00000, 6.81744 ..."
27,Knittkuhl,42.066667,"POLYGON Z ((6.87875 51.26294 0.00000, 6.87894 ..."
28,Lichtenbroich,50.006506,"POLYGON Z ((6.80387 51.28707 0.00000, 6.80387 ..."
29,Lierenfeld,50.019672,"POLYGON Z ((6.84003 51.22000 0.00000, 6.83979 ..."
30,Lohausen,47.333935,"POLYGON Z ((6.80370 51.28715 0.00000, 6.79951 ..."
31,Ludenberg,46.111016,"POLYGON Z ((6.87907 51.26115 0.00000, 6.87905 ..."
32,Lörick,45.645251,"POLYGON Z ((6.74610 51.25203 0.00000, 6.74380 ..."
33,Mörsenbroich,47.952467,"POLYGON Z ((6.82216 51.25095 0.00000, 6.82216 ..."
34,Niederkassel,49.013447,"POLYGON Z ((6.76824 51.23500 0.00000, 6.76261 ..."
35,Oberbilk,52.549721,"POLYGON Z ((6.82593 51.19570 0.00000, 6.82593 ..."
36,Oberkassel,50.722032,"POLYGON Z ((6.76868 51.23195 0.00000, 6.76868 ..."
37,Pempelfort,53.410959,"POLYGON Z ((6.79800 51.23008 0.00000, 6.79804 ..."
38,Rath,50.001757,"POLYGON Z ((6.86739 51.26844 0.00000, 6.86574 ..."
39,Reisholz,48.47557,"POLYGON Z ((6.87124 51.17034 0.00000, 6.87032 ..."
40,Stadtmitte,55.388309,"POLYGON Z ((6.79958 51.22495 0.00000, 6.79952 ..."
41,Stockum,49.762687,"POLYGON Z ((6.76303 51.26172 0.00000, 6.76303 ..."
42,Unterbach,46.885546,"POLYGON Z ((6.92130 51.19269 0.00000, 6.92104 ..."
43,Unterbilk,52.964286,"POLYGON Z ((6.77694 51.21900 0.00000, 6.77694 ..."
44,Unterrath,48.799368,"POLYGON Z ((6.79770 51.27522 0.00000, 6.79669 ..."
45,Urdenbach,46.1933,"POLYGON Z ((6.89610 51.13527 0.00000, 6.89609 ..."
46,Vennhausen,46.570847,"POLYGON Z ((6.88052 51.20617 0.00000, 6.88026 ..."
47,Volmerswerth,47.922794,"POLYGON Z ((6.77385 51.18519 0.00000, 6.77383 ..."
48,Wersten,49.582969,"POLYGON Z ((6.84422 51.18866 0.00000, 6.84421 ..."
49,Wittlaer,45.046811,"POLYGON Z ((6.76623 51.31355 0.00000, 6.76617 ..."

In [18]:
df3 = gpd.GeoDataFrame(Bezirk_NACHT.merge(df, on='Neighborhood', how='left'))
df3.rename(columns={'DB_NACHT':'Avg. DB_NACHT','GEO':'geometry'}, inplace=True)
df3['Avg. DB_NACHT'] = df3['Avg. DB_NACHT'].round(decimals = 2)
df3

,Neighborhood,Avg. DB_NACHT,geometry
0,Altstadt,48.22,"POLYGON Z ((6.77727 51.23037 0.00000, 6.77728 ..."
1,Angermund,42.9,"POLYGON Z ((6.80952 51.34292 0.00000, 6.80943 ..."
2,Benrath,50.31,"POLYGON Z ((6.90020 51.16715 0.00000, 6.89997 ..."
3,Bilk,51.14,"POLYGON Z ((6.80838 51.19328 0.00000, 6.80811 ..."
4,Carlstadt,51.89,"POLYGON Z ((6.77569 51.22498 0.00000, 6.77565 ..."
5,Derendorf,52.22,"POLYGON Z ((6.79620 51.24362 0.00000, 6.79372 ..."
6,Düsseltal,51.83,"POLYGON Z ((6.82162 51.23851 0.00000, 6.82160 ..."
7,Eller,50.11,"POLYGON Z ((6.87957 51.19002 0.00000, 6.87853 ..."
8,Flehe,52.93,"POLYGON Z ((6.80396 51.18062 0.00000, 6.80367 ..."
9,Flingern Nord,51.23,"POLYGON Z ((6.83976 51.22046 0.00000, 6.83952 ..."
10,Flingern Süd,52.79,"POLYGON Z ((6.82396 51.22391 0.00000, 6.82386 ..."
11,Friedrichstadt,54.89,"POLYGON Z ((6.79216 51.21716 0.00000, 6.79204 ..."
12,Garath,49.3,"POLYGON Z ((6.91823 51.14008 0.00000, 6.91627 ..."
13,Gerresheim,47.42,"POLYGON Z ((6.88005 51.22802 0.00000, 6.87998 ..."
14,Golzheim,51.63,"POLYGON Z ((6.78206 51.24235 0.00000, 6.78196 ..."
15,Grafenberg,49.82,"POLYGON Z ((6.83942 51.23641 0.00000, 6.83817 ..."
16,Hafen,52.38,"POLYGON Z ((6.76573 51.21917 0.00000, 6.76574 ..."
17,Hamm,49.04,"POLYGON Z ((6.75856 51.21041 0.00000, 6.75853 ..."
18,Hassels,51.24,"POLYGON Z ((6.90574 51.17675 0.00000, 6.90570 ..."
19,Heerdt,53.48,"POLYGON Z ((6.73560 51.23767 0.00000, 6.73399 ..."
20,Hellerhof,49.34,"POLYGON Z ((6.92512 51.13657 0.00000, 6.92478 ..."
21,Himmelgeist,46.02,"POLYGON Z ((6.81809 51.14564 0.00000, 6.81803 ..."
22,Holthausen,49.92,"POLYGON Z ((6.85530 51.18514 0.00000, 6.85408 ..."
23,Hubbelrath,47.65,"POLYGON Z ((6.93993 51.27255 0.00000, 6.93985 ..."
24,Itter,47.2,"POLYGON Z ((6.82898 51.15593 0.00000, 6.82890 ..."
25,Kaiserswerth,48.61,"POLYGON Z ((6.75248 51.30776 0.00000, 6.75246 ..."
26,Kalkum,45.48,"POLYGON Z ((6.81745 51.32094 0.00000, 6.81744 ..."
27,Knittkuhl,42.07,"POLYGON Z ((6.87875 51.26294 0.00000, 6.87894 ..."
28,Lichtenbroich,50.01,"POLYGON Z ((6.80387 51.28707 0.00000, 6.80387 ..."
29,Lierenfeld,50.02,"POLYGON Z ((6.84003 51.22000 0.00000, 6.83979 ..."
30,Lohausen,47.33,"POLYGON Z ((6.80370 51.28715 0.00000, 6.79951 ..."
31,Ludenberg,46.11,"POLYGON Z ((6.87907 51.26115 0.00000, 6.87905 ..."
32,Lörick,45.65,"POLYGON Z ((6.74610 51.25203 0.00000, 6.74380 ..."
33,Mörsenbroich,47.95,"POLYGON Z ((6.82216 51.25095 0.00000, 6.82216 ..."
34,Niederkassel,49.01,"POLYGON Z ((6.76824 51.23500 0.00000, 6.76261 ..."
35,Oberbilk,52.55,"POLYGON Z ((6.82593 51.19570 0.00000, 6.82593 ..."
36,Oberkassel,50.72,"POLYGON Z ((6.76868 51.23195 0.00000, 6.76868 ..."
37,Pempelfort,53.41,"POLYGON Z ((6.79800 51.23008 0.00000, 6.79804 ..."
38,Rath,50.0,"POLYGON Z ((6.86739 51.26844 0.00000, 6.86574 ..."
39,Reisholz,48.48,"POLYGON Z ((6.87124 51.17034 0.00000, 6.87032 ..."
40,Stadtmitte,55.39,"POLYGON Z ((6.79958 51.22495 0.00000, 6.79952 ..."
41,Stockum,49.76,"POLYGON Z ((6.76303 51.26172 0.00000, 6.76303 ..."
42,Unterbach,46.89,"POLYGON Z ((6.92130 51.19269 0.00000, 6.92104 ..."
43,Unterbilk,52.96,"POLYGON Z ((6.77694 51.21900 0.00000, 6.77694 ..."
44,Unterrath,48.8,"POLYGON Z ((6.79770 51.27522 0.00000, 6.79669 ..."
45,Urdenbach,46.19,"POLYGON Z ((6.89610 51.13527 0.00000, 6.89609 ..."
46,Vennhausen,46.57,"POLYGON Z ((6.88052 51.20617 0.00000, 6.88026 ..."
47,Volmerswerth,47.92,"POLYGON Z ((6.77385 51.18519 0.00000, 6.77383 ..."
48,Wersten,49.58,"POLYGON Z ((6.84422 51.18866 0.00000, 6.84421 ..."
49,Wittlaer,45.05,"POLYGON Z ((6.76623 51.31355 0.00000, 6.76617 ..."

In [19]:
from keplergl import KeplerGl
map_1 = KeplerGl(height=1000)

map_1.add_data(data=df2, name='dus_noise')

map_1

# four steps of fill color Hex: [#FEF001, #FD9A01, #FD6104, #F00505]

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(data={'dus_noise': {'index': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2…

In [20]:
map_1.save_to_html(file_name='dus_mapday.html')

Map saved to dus_mapday.html!

In [21]:
from keplergl import KeplerGl
map_2 = KeplerGl(height=1000)

map_2.add_data(data=df3, name='dus_noise')

map_2

# four steps of fill color Hex: [#FEF001, #FD9A01, #FD6104, #F00505]

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(data={'dus_noise': {'index': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2…

In [22]:
map_2.save_to_html(file_name='dus_mapnight.html')

Map saved to dus_mapnight.html!